"""empty message

Revision ID: 005479603886
Revises: e8e08f7b94a6
Create Date: 2019-05-12 23:32:58.956700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005479603886'
down_revision = 'e8e08f7b94a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('dni', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('total_amount', sa.Float(precision=2), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_manager', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
