"""empty message

Revision ID: 364422da7e12
Revises: 
Create Date: 2019-05-11 06:27:17.465863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364422da7e12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sandwiches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bar_sandwiches',
    sa.Column('bar_id', sa.Integer(), nullable=False),
    sa.Column('sandwich_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ),
    sa.ForeignKeyConstraint(['sandwich_id'], ['sandwiches.id'], ),
    sa.PrimaryKeyConstraint('bar_id', 'sandwich_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bar_sandwiches')
    op.drop_table('sandwiches')
    op.drop_table('bars')
    # ### end Alembic commands ###
